### PR TITLE
Convert descriptor types to StandardDescriptorNumbers

### PR DESCRIPTION
**Pull request by twam**

### CODE REVIEW

**Comment by ktemkin** [comment]
This doesn't seem right, for a number of reasons:

1. Not every type is going to be encapsulated here, so we'll want to be able to handle these as raw integers.
2. There's almost definitely a typo in the code `type(... == int)`.

**Comment by twam** [comment]
You're right about the code 🙈.

Would adding a try-except block a solution and stay with the int of no conversion is possible?

**Comment by twam** [comment]
Any updates? 😢

**Comment by antoinevg** [comment]
My apologies for the long delay.

Merged, thank you!

**Pull request merged**
